var myFullName;
console.log(myFullName);
myFullName="Snehankita Kakade";
console.log(myFullName);
myFullName="Snehankita Shashikant Kakade";
console.log(myFullName);
var myLove="I Love only JS";
console.log(myLove);
var firstName="Snehankita";
console.log(firstName);
var lastName="Kakade";
console.log(lastName);
var age="26";
console.log(age);
var address="Pune";
console.log(address);
var pincode="431126";
console.log(pincode);
var gender="Female";
console.log(gender);
var isMarried="Yes";
console.log(isMarried);
